[package]
name = "cheatbook"
version = "0.1.0"
edition = "2021"

[dependencies]
# bevy = { version = "0.8" }
bevy = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
image = "0.24.2"
winit = "0.26.1"
